### ISSUE TITLE
some websites dont work with middle squid

### ISSUE THREAD

**Issue by mullex** [cfillion/middle_squid#2]
I set up middle_squid and most of the websites work fine.But for some sites like qq.com, it got the following error.How to fix this?

ERROR

The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: http://127.0.0.1:53426/cc3daea4-a546-43db-b7a6-b61949da2b7a

Zero Sized Reply

Squid did not receive any data for this request.

http://127.0.0.1:53426/cc3daea4-a546-43db-b7a6-b61949da2b7a returns the error below.
Your cache administrator is webmaster.

[MiddleSquid] Errno::ECONNREFUSED

**Comment by cfillion** [comment]
Hi, sorry for the late reply.

The error message indicates the webserver at qq.com was refusing incoming connections, but it seems to be fine now.

You can catch this kind of errors by testing if the http status code returned by `download_like`  is 520:

``` ruby
intercept {|req, res|
  status, headers, body = download_like req, uri

  if status == 520
    # MiddleSquid was unable to fetch the requested page from the remote webserver

    # we can generate a user-frendly error page, to replace the default one:
    headers['Content-Type'] = 'text/html'
    body = File.read("/var/squid/download_error.html")
  end

  [status, headers, body]
}
```
